#include "instructions.h"
#include <stdio.h>

static void nop(CPU *cpu) {
  printf("NOP\n");
}

Instruction instructions[256] = {
  { "NOP ", 1, 4, nop },
  { "LD BC, d16", 3, 12, NULL },
  { "LD BC, A", 1, 8, NULL },
  { "INC BC", 1, 8, NULL },
  { "INC B", 1, 4, NULL },
  { "DEC B", 1, 4, NULL },
  { "LD B, d8", 2, 8, NULL },
  { "RLCA ", 1, 4, NULL },
  { "LD a16, SP", 3, 20, NULL },
  { "ADD HL, BC", 1, 8, NULL },
  { "LD A, BC", 1, 8, NULL },
  { "DEC BC", 1, 8, NULL },
  { "INC C", 1, 4, NULL },
  { "DEC C", 1, 4, NULL },
  { "LD C, d8", 2, 8, NULL },
  { "RRCA ", 1, 4, NULL },
  { "STOP d8", 2, 4, NULL },
  { "LD DE, d16", 3, 12, NULL },
  { "LD DE, A", 1, 8, NULL },
  { "INC DE", 1, 8, NULL },
  { "INC D", 1, 4, NULL },
  { "DEC D", 1, 4, NULL },
  { "LD D, d8", 2, 8, NULL },
  { "RLA ", 1, 4, NULL },
  { "JR r8", 2, 12, NULL },
  { "ADD HL, DE", 1, 8, NULL },
  { "LD A, DE", 1, 8, NULL },
  { "DEC DE", 1, 8, NULL },
  { "INC E", 1, 4, NULL },
  { "DEC E", 1, 4, NULL },
  { "LD E, d8", 2, 8, NULL },
  { "RRA ", 1, 4, NULL },
  { "JR NZ, r8", 2, 12, NULL },
  { "LD HL, d16", 3, 12, NULL },
  { "LD HL, A", 1, 8, NULL },
  { "INC HL", 1, 8, NULL },
  { "INC H", 1, 4, NULL },
  { "DEC H", 1, 4, NULL },
  { "LD H, d8", 2, 8, NULL },
  { "DAA ", 1, 4, NULL },
  { "JR Z, r8", 2, 12, NULL },
  { "ADD HL, HL", 1, 8, NULL },
  { "LD A, HL", 1, 8, NULL },
  { "DEC HL", 1, 8, NULL },
  { "INC L", 1, 4, NULL },
  { "DEC L", 1, 4, NULL },
  { "LD L, d8", 2, 8, NULL },
  { "CPL ", 1, 4, NULL },
  { "JR NC, r8", 2, 12, NULL },
  { "LD SP, d16", 3, 12, NULL },
  { "LD HL, A", 1, 8, NULL },
  { "INC SP", 1, 8, NULL },
  { "INC HL", 1, 12, NULL },
  { "DEC HL", 1, 12, NULL },
  { "LD HL, d8", 2, 12, NULL },
  { "SCF ", 1, 4, NULL },
  { "JR C, r8", 2, 12, NULL },
  { "ADD HL, SP", 1, 8, NULL },
  { "LD A, HL", 1, 8, NULL },
  { "DEC SP", 1, 8, NULL },
  { "INC A", 1, 4, NULL },
  { "DEC A", 1, 4, NULL },
  { "LD A, d8", 2, 8, NULL },
  { "CCF ", 1, 4, NULL },
  { "LD B, B", 1, 4, NULL },
  { "LD B, C", 1, 4, NULL },
  { "LD B, D", 1, 4, NULL },
  { "LD B, E", 1, 4, NULL },
  { "LD B, H", 1, 4, NULL },
  { "LD B, L", 1, 4, NULL },
  { "LD B, HL", 1, 8, NULL },
  { "LD B, A", 1, 4, NULL },
  { "LD C, B", 1, 4, NULL },
  { "LD C, C", 1, 4, NULL },
  { "LD C, D", 1, 4, NULL },
  { "LD C, E", 1, 4, NULL },
  { "LD C, H", 1, 4, NULL },
  { "LD C, L", 1, 4, NULL },
  { "LD C, HL", 1, 8, NULL },
  { "LD C, A", 1, 4, NULL },
  { "LD D, B", 1, 4, NULL },
  { "LD D, C", 1, 4, NULL },
  { "LD D, D", 1, 4, NULL },
  { "LD D, E", 1, 4, NULL },
  { "LD D, H", 1, 4, NULL },
  { "LD D, L", 1, 4, NULL },
  { "LD D, HL", 1, 8, NULL },
  { "LD D, A", 1, 4, NULL },
  { "LD E, B", 1, 4, NULL },
  { "LD E, C", 1, 4, NULL },
  { "LD E, D", 1, 4, NULL },
  { "LD E, E", 1, 4, NULL },
  { "LD E, H", 1, 4, NULL },
  { "LD E, L", 1, 4, NULL },
  { "LD E, HL", 1, 8, NULL },
  { "LD E, A", 1, 4, NULL },
  { "LD H, B", 1, 4, NULL },
  { "LD H, C", 1, 4, NULL },
  { "LD H, D", 1, 4, NULL },
  { "LD H, E", 1, 4, NULL },
  { "LD H, H", 1, 4, NULL },
  { "LD H, L", 1, 4, NULL },
  { "LD H, HL", 1, 8, NULL },
  { "LD H, A", 1, 4, NULL },
  { "LD L, B", 1, 4, NULL },
  { "LD L, C", 1, 4, NULL },
  { "LD L, D", 1, 4, NULL },
  { "LD L, E", 1, 4, NULL },
  { "LD L, H", 1, 4, NULL },
  { "LD L, L", 1, 4, NULL },
  { "LD L, HL", 1, 8, NULL },
  { "LD L, A", 1, 4, NULL },
  { "LD HL, B", 1, 8, NULL },
  { "LD HL, C", 1, 8, NULL },
  { "LD HL, D", 1, 8, NULL },
  { "LD HL, E", 1, 8, NULL },
  { "LD HL, H", 1, 8, NULL },
  { "LD HL, L", 1, 8, NULL },
  { "HALT ", 1, 4, NULL },
  { "LD HL, A", 1, 8, NULL },
  { "LD A, B", 1, 4, NULL },
  { "LD A, C", 1, 4, NULL },
  { "LD A, D", 1, 4, NULL },
  { "LD A, E", 1, 4, NULL },
  { "LD A, H", 1, 4, NULL },
  { "LD A, L", 1, 4, NULL },
  { "LD A, HL", 1, 8, NULL },
  { "LD A, A", 1, 4, NULL },
  { "ADD A, B", 1, 4, NULL },
  { "ADD A, C", 1, 4, NULL },
  { "ADD A, D", 1, 4, NULL },
  { "ADD A, E", 1, 4, NULL },
  { "ADD A, H", 1, 4, NULL },
  { "ADD A, L", 1, 4, NULL },
  { "ADD A, HL", 1, 8, NULL },
  { "ADD A, A", 1, 4, NULL },
  { "ADC A, B", 1, 4, NULL },
  { "ADC A, C", 1, 4, NULL },
  { "ADC A, D", 1, 4, NULL },
  { "ADC A, E", 1, 4, NULL },
  { "ADC A, H", 1, 4, NULL },
  { "ADC A, L", 1, 4, NULL },
  { "ADC A, HL", 1, 8, NULL },
  { "ADC A, A", 1, 4, NULL },
  { "SUB B", 1, 4, NULL },
  { "SUB C", 1, 4, NULL },
  { "SUB D", 1, 4, NULL },
  { "SUB E", 1, 4, NULL },
  { "SUB H", 1, 4, NULL },
  { "SUB L", 1, 4, NULL },
  { "SUB HL", 1, 8, NULL },
  { "SUB A", 1, 4, NULL },
  { "SBC A, B", 1, 4, NULL },
  { "SBC A, C", 1, 4, NULL },
  { "SBC A, D", 1, 4, NULL },
  { "SBC A, E", 1, 4, NULL },
  { "SBC A, H", 1, 4, NULL },
  { "SBC A, L", 1, 4, NULL },
  { "SBC A, HL", 1, 8, NULL },
  { "SBC A, A", 1, 4, NULL },
  { "AND B", 1, 4, NULL },
  { "AND C", 1, 4, NULL },
  { "AND D", 1, 4, NULL },
  { "AND E", 1, 4, NULL },
  { "AND H", 1, 4, NULL },
  { "AND L", 1, 4, NULL },
  { "AND HL", 1, 8, NULL },
  { "AND A", 1, 4, NULL },
  { "XOR B", 1, 4, NULL },
  { "XOR C", 1, 4, NULL },
  { "XOR D", 1, 4, NULL },
  { "XOR E", 1, 4, NULL },
  { "XOR H", 1, 4, NULL },
  { "XOR L", 1, 4, NULL },
  { "XOR HL", 1, 8, NULL },
  { "XOR A", 1, 4, NULL },
  { "OR B", 1, 4, NULL },
  { "OR C", 1, 4, NULL },
  { "OR D", 1, 4, NULL },
  { "OR E", 1, 4, NULL },
  { "OR H", 1, 4, NULL },
  { "OR L", 1, 4, NULL },
  { "OR HL", 1, 8, NULL },
  { "OR A", 1, 4, NULL },
  { "CP B", 1, 4, NULL },
  { "CP C", 1, 4, NULL },
  { "CP D", 1, 4, NULL },
  { "CP E", 1, 4, NULL },
  { "CP H", 1, 4, NULL },
  { "CP L", 1, 4, NULL },
  { "CP HL", 1, 8, NULL },
  { "CP A", 1, 4, NULL },
  { "RET NZ", 1, 20, NULL },
  { "POP BC", 1, 12, NULL },
  { "JP NZ, a16", 3, 16, NULL },
  { "JP a16", 3, 16, NULL },
  { "CALL NZ, a16", 3, 24, NULL },
  { "PUSH BC", 1, 16, NULL },
  { "ADD A, d8", 2, 8, NULL },
  { "RST 00H", 1, 16, NULL },
  { "RET Z", 1, 20, NULL },
  { "RET ", 1, 16, NULL },
  { "JP Z, a16", 3, 16, NULL },
  { "PREFIX ", 1, 4, NULL },
  { "CALL Z, a16", 3, 24, NULL },
  { "CALL a16", 3, 24, NULL },
  { "ADC A, d8", 2, 8, NULL },
  { "RST 08H", 1, 16, NULL },
  { "RET NC", 1, 20, NULL },
  { "POP DE", 1, 12, NULL },
  { "JP NC, a16", 3, 16, NULL },
  { "ILLEGAL_D3 ", 1, 4, NULL },
  { "CALL NC, a16", 3, 24, NULL },
  { "PUSH DE", 1, 16, NULL },
  { "SUB d8", 2, 8, NULL },
  { "RST 10H", 1, 16, NULL },
  { "RET C", 1, 20, NULL },
  { "RETI ", 1, 16, NULL },
  { "JP C, a16", 3, 16, NULL },
  { "ILLEGAL_DB ", 1, 4, NULL },
  { "CALL C, a16", 3, 24, NULL },
  { "ILLEGAL_DD ", 1, 4, NULL },
  { "SBC A, d8", 2, 8, NULL },
  { "RST 18H", 1, 16, NULL },
  { "LDH a8, A", 2, 12, NULL },
  { "POP HL", 1, 12, NULL },
  { "LD C, A", 1, 8, NULL },
  { "ILLEGAL_E3 ", 1, 4, NULL },
  { "ILLEGAL_E4 ", 1, 4, NULL },
  { "PUSH HL", 1, 16, NULL },
  { "AND d8", 2, 8, NULL },
  { "RST 20H", 1, 16, NULL },
  { "ADD SP, r8", 2, 16, NULL },
  { "JP HL", 1, 4, NULL },
  { "LD a16, A", 3, 16, NULL },
  { "ILLEGAL_EB ", 1, 4, NULL },
  { "ILLEGAL_EC ", 1, 4, NULL },
  { "ILLEGAL_ED ", 1, 4, NULL },
  { "XOR d8", 2, 8, NULL },
  { "RST 28H", 1, 16, NULL },
  { "LDH A, a8", 2, 12, NULL },
  { "POP AF", 1, 12, NULL },
  { "LD A, C", 1, 8, NULL },
  { "DI ", 1, 4, NULL },
  { "ILLEGAL_F4 ", 1, 4, NULL },
  { "PUSH AF", 1, 16, NULL },
  { "OR d8", 2, 8, NULL },
  { "RST 30H", 1, 16, NULL },
  { "LD HL, SP, r8", 2, 12, NULL },
  { "LD SP, HL", 1, 8, NULL },
  { "LD A, a16", 3, 16, NULL },
  { "EI ", 1, 4, NULL },
  { "ILLEGAL_FC ", 1, 4, NULL },
  { "ILLEGAL_FD ", 1, 4, NULL },
  { "CP d8", 2, 8, NULL },
  { "RST 38H", 1, 16, NULL }
};
